### PR TITLE
Adds Ampeg, BOSS, Catalinbread, Darkglass, Donner, EarthQuaker Devices, Electro-Harmonix, Friedman, J. Rockett, Jackson Audio, Keeley, Line 6, and ThorpyFX pedals

### LINKED ISSUE #1660: Multiple FTelettronica pedals have empty background images
Many pedals from the FTelettronica category do not show up when selected. Nothing appears when a user selects the pedal, however, an empty div can still be selected and interacted with.

The pedals in question:

- Anonymous Flange
- Atrocity Distortion
- Black Hole Analog Octaver
- Catastrophizer Distortion
- Cotton Candy Digital Reverb
- Das Model
- Dystopian Fuzz
- Echo Maniac Kid

Tested in both Firefox and Chrome

### LINKED ISSUE #1674: Electro-Harmonix Pico Platform Compressor/Limiter
Screenshot 2023-09-30 202602

3.63 x 2.13

Thank you

### PR DESCRIPTION
**Pull request by XlosVSM**
**Adds**
- Ampeg SGT-DI
- BBE Sonic Stomp Mini
- BOSS GT-1
- BOSS ME-90
- BOSS NS-1X
- BOSS RC-2
- Catalinbread Sabbra Cadabra (Clearwell Edition)
- Catalinbread Soft Focus Reverb (Shoegaze Purple)
- Darkglass NSG
- Donner Circle Looper
- Donner Dark Mouse
- Donner Dumbal Drive
- Donner Extreme Driver
- Donner Golden Tremolo
- Donner Island Delay
- Donner Morpher
- Donner Vintaverb
- EarthQuaker Devices Aurelius
- EarthQuaker Devices Special Cranker (Blue Steel)
- Electro-Harmonix Lizard Queen (Big Box)
- Electro-Harmonix Pico Platform
- Formula B Supa Tank
- Friedman BE-OD (Artisan Edition)
- Friedman BE-OD Deluxe (Clockworks Edition)
- Friedman Sir-Compre (Artisan Edition)
- Fulltone GT-500
- GUPTech SUN
- J. Rockett Audio Designs The Jeff Archer (Copper Plated)
- Jackson Audio Golden Boy (Rose)
- Keeley Halo (Andy Apple Red)
- Keeley Katana (New Light Pink)
- Kingsley Page TS
- Line 6 Helix (Space Gray)
- Mooer TF-16S
- MOYO Mini Expression
- MOYO Mini Volume
- PastFX Patriarch
- PastFX Powerbooster
- Pladask Elekstrisk Falma V2
- Sonuus Voluum
- ThorpyFX ER-2 Uni-Vibe

**Fixes**
- BOSS ML-2 item name
- Death by Audio Interstellar Overdriver image
- Dimensions of some Donner pedals
- DOD Carcosa image improved
- DOD moved to its own brand
- File name changes for spelling
- GigRig Three 2 One dimensions
- MXR Super Comp duplicate removed
- MXR Super Comp image improved
- Restores brands on some pedals
- Restores Retro-Sonic images
- ThorpyFX brand name capitalised properly
- Twinote BBD Chorus dimensions

closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1251
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1443
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1446
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1453
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1469
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1472
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1473
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1483
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1484
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1485
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1486
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1513
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1514
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1540
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1553
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1560
closes https://github.com/PedalPlayground/PedalPlayground.github.io/issues/1573
closes #1660 
closes #1674

### CODE REVIEW

**Comment by XlosVSM** [comment]
@tehtrav PR is ready to merge

**Comment by XlosVSM** [comment]
@tehtrav ready to merge

**Comment by XlosVSM** [comment]
@tehtrav PR ready

**Comment by tehtrav** [comment]
@XlosVSM can you tell me more about what all you've done in this PR? 700 changes and I see stuff like "removed app folder" so I'm pretty hesitant to pull this all in without more detail

**Comment by ArislanShiva** [comment]
Maybe make a fresh PR with only the pedals you added?  It's too risky to pull all the rest in, IMO.

**Pull request closed without merging**
