### PR TITLE
Adds Vox V861 and fixes EBS

### PR DESCRIPTION
**Pull request by XlosVSM**
**IMPORTANT: IGNORE EVERYTHING BEFORE 86a3959. They have been reverted and do not change anything as of now**

**Adds**
- Vox V861

**Fixes**
- EBS DPhaser image
- EBS Microbass 3 name

### CODE REVIEW

**Comment by ArislanShiva** [comment]
I've already fixed all issues with EBS in #1817.

Recommend that you redownload the current version of the repo so you can start from a truly clean slate.   Travis probably isn't gonna wanna pull something with a ton of sketchy reversions in.

**Comment by XlosVSM** [comment]
@ArislanShiva Your fix for DPhaser is just to delete it

**Comment by ArislanShiva** [comment]
> @ArislanShiva Your fix for DPhaser is just to delete it

It's been added back, I just haven't pushed the changes yet.

**Comment by ArislanShiva** [comment]
I've incorporated your updates into #2002 to get it pushed.  Can go ahead and close this one out.

**Pull request closed without merging**
