### PR TITLE
Add EBS Microbass 3

### PR DESCRIPTION
**Pull request by TheIronMustache**
First shot at contributing, hopefully it is being executed properly. Will add corresponding images following this submission. Also first time using github so that's cool... anyway, just realized uploads disabled so I attached a zip file with both the under 350 and under 800 transparent png24s. I have a ton of images that are not available here that are already prepped for upload once I figure this all out. I typically do all of my layouts in InDesign but this is a way better platform.

[ebs-microbass3_BothSizes.zip](https://github.com/PedalPlayground/PedalPlayground.github.io/files/9462069/ebs-microbass3_BothSizes.zip)

### CODE REVIEW

**Comment by ArislanShiva** [comment]
Hey, thanks for contributing!

You should upload your files to [your own forked repository](https://github.com/TheIronMustache/PedalPlayground.github.io), then create a pull request from there.  Then github will compare any differences between your repo and the main project repo and create a list of changes/files to push.

**Comment by TheIronMustache** [comment]
> Hey, thanks for contributing!
> 
> You should upload your files to [your own forked repository](https://github.com/TheIronMustache/PedalPlayground.github.io), then create a pull request from there. Then github will compare any differences between your repo and the main project repo and create a list of changes/files to push.


Great, hopefully I just did it correctly. Concepts starting to make more sense.

Thanks!

**Comment by tehtrav** [comment]
@TheIronMustache I'm not seeing your images as a part of the PR. Could you double check that you've added them to your branch?

**Comment by TheIronMustache** [comment]
> Hey, thanks for contributing!
> 
> You should upload your files to [your own forked repository](https://github.com/TheIronMustache/PedalPlayground.github.io), then create a pull request from there. Then github will compare any differences between your repo and the main project repo and create a list of changes/files to push.

Hey sorry for the absurdly late reply here. I am wicked busy lol... I haven't had time to go through everything here to figure out what I am doing wrong to get my images committed but I have a bunch of .pngs that could be added. Is there anyone here that you know of that would maybe want to facilitate the committing process if I am able to get the images for them?

I can knock out an image in under 2min so I'd be willing to contribute as many new models as anyone could need or request in that scenario. Other than that I will have to spend some more time figuring this all out. I have approximately 0 experience with Github but I am a technical graphics person by profession.

**Comment by ArislanShiva** [comment]
I've folded this into #1502 to get it pushed.  Can go ahead and close this PR.

**Pull request closed without merging**
