### PR TITLE
Adds LastGasp pedals, Roland VT-3 and TB-3, gig-fx pedals, Lightning Wave pedals, all M-VAVE products

### LINKED ISSUE #1419: Pedal Request: Lightning Wave Astro
Lightning Wave
Astro 
Dimensions: 3.7 x 4.86
LightningWave-astro

### LINKED ISSUE #1835: Pedal Request: Laney Black Country Customs Monolith
118mm x 65mm

image

### LINKED ISSUE #1836: New Pedal Request: Free The Tone Gigs Boson
Dimensions: 2.83 x 4.53

image

### LINKED ISSUE #1837: Pedal request: Henretta Engineering Green Zapper
IMG_8182

2” x 2”

### LINKED ISSUE #1907: M-VAVE Tank G
12,20(L) x 2,55(W) x 1,57(H) in

### PR DESCRIPTION
**Pull request by Oakwooooood**
LastGasp Art Laboratories : 
- Transroom
- Tone Mosaique

Roland :
- VT-3
- TB-3

gig-fx :
- Chopper
- Pro Chop
- Kilo Wah
- Mega Wah
- VOD Variable Overdrive

Lightning Wave :
- Doom
- Astro

Korg Volcas :

- Bass
- Sample
- Drum
- FM
- FM 2
- Modular
- Nubass
- Kick
- Mix
- Keys
- Beats

Adds all M-VAVE products

- Isolated Power
- Mini EFX
- Cube Magic
- Mini Amp
- ABY Box
- Cube Baby Bass
- Mini Universe
- Cube Sugar
- Pedal Power
- Cube Baby AC
- Cube Baby
- Cube Turner Pro
- Tank G
- Cube Turner Plus
- Overdrive DB
- Looper
- Noise Gate
- Delay
- Fuzz
- DIG Pitch
- Booster
- DIG Reverb
- H8
- Overdrive BLUES
- Phaser
- Tuner
- Dist MT1
- Tremolo
- Overdrive Amp
- Distorsion SC1
- Overdrive TS
- Dist British
- Compressor
- DIG Delay
- Looper Plus
- Chocolate

closes #1419 
Lightning Wave Astro 
closes #1835 
Laney Black Country Customs Monolith 
closes #1836 
Free The Tone Gigs Boson 
closes #1837 
Henretta Engineering Green Zapper 
closes #1907 
M-VAVE Tank G

### CODE REVIEW

**Comment by Oakwooooood** [comment]
Hello @tehtrav , is there a problem in my request ? Something I should change ? thanks!

**Comment by Oakwooooood** [comment]
Adds Roland VT 3

**Comment by Oakwooooood** [comment]
Hi @ArislanShiva, sorry to bother you. I spent a lot of time adding these pedals and was wondering if something is off with my resquest before Tehtrav reviews it! Could you inspect it and tell me what to change if you have the time ?
Thank you

**Comment by ArislanShiva** [comment]
> Hi @ArislanShiva, sorry to bother you. I spent a lot of time adding these pedals and was wondering if something is off with my request and would like it to be good to go before Tehtrav reviews it! Could you inspect it and tell me what to change if you have the time ? Thank you

Just have to remain patient.  Travis will pull it in when he's ready.

**Comment by Oakwooooood** [comment]
Thank you, I was afraid there was something wrong with it

**Comment by ArislanShiva** [comment]
Hey, just a suggestion:  

If you use the [Github Desktop client](https://desktop.github.com/) you can push all your changes in one go, instead of having to upload individual files manually.

**Comment by Oakwooooood** [comment]
Thanks, I'll try it

**Comment by Oakwooooood** [comment]
So what is happening here, we wait for months and then he merges some without looking into the others ? It's been a few times like that, please don't allow random people to contribute in this case. I lost time doing all this.

**Pull request closed without merging**
