### PR TITLE
Added Line 6 Pod Express Guitar

### PR DESCRIPTION
**Pull request by brs928**
Added Line 6 Pod Express Guitar

### CODE REVIEW

**Comment by ArislanShiva** [comment]
Thanks, but these were already added in #1817

**Comment by brs928** [comment]
That's strange, it doesn't appear for me when I visit the website on my
computer or my phone. Can you double check that it works for you?

**Comment by ArislanShiva** [comment]
#1817 hasn't been pulled in to the main project yet, but the Pod Express was added to it on release day.

Go ahead and close this PR when possible.  Thanks.

**Comment by brs928** [comment]
Got it, thanks!

**Pull request closed without merging**
