### PR TITLE
Fixed item boundaries rotation on pedalboard and pedal.

### LINKED ISSUE #88: Rotated item boundaries
When dragging rotated items the item boundaries are not rotated, this problem is most noticeable when positioning rotated pedals near the canvas edge, when the rotated item should be able to butt-up against the canvas edge, but the non-rotated item boundary is stopping it from being possible.

### PR DESCRIPTION
**Pull request by lucaromanoxyz**
Close #88

### CODE REVIEW

**Comment by ArislanShiva** [comment]
Hey there!   I'm gonna include this in #1901 to ensure your changes gets pulled in asap.  

When possible please go ahead and close this PR.  Thanks!

**Comment by lucaromanoxyz** [comment]
If I close it, github says that there are no merged commit

**Comment by ArislanShiva** [comment]
Oh sorry, I just added your changes manually to my commit.    I didn't even realize it was possible to merge commits... now in hindsight that seems so obvious haha.

**Comment by ArislanShiva** [comment]
Just FYI your commit was pulled in and is live on the site now.  Can go ahead and close this one out.

**Pull request closed without merging**
