### PR TITLE
Add Yellowcake Furry Burrito

### PR DESCRIPTION
**Pull request by slowpogo**
First time contributor and new to Github. Hoping to get the hang of this as I have several pedals to add. I created my own fork, uploaded pics and edited pedals.json, please let me know if I'm not doing this right (which is very likely)

### CODE REVIEW

**Comment by slowpogo** [comment]
first time user here, what happens next? this passed checks a while ago but still needs to be merged

**Comment by XlosVSM** [comment]
> first time user here, what happens next? this passed checks a while ago but still needs to be merged

You have to wait for @tehtrav to accept the pull request

**Comment by slowpogo** [comment]
They've accepted several more recent requests though. So I can't help but wonder if mine was overlooked or is unacceptable in some way

**Comment by ArislanShiva** [comment]
I've folded this into #1502 to get it pushed. Can go ahead and close this PR.

**Pull request closed without merging**
